config/routes.rb
Rails.application.routes.draw do
  
  root 'bootstrap_library#index'
  get 'bootstrap_library/bootstrap_library/:id', to: 'bootstrap_library#show'
  resources :bootstrap_library
  

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :type
end

app/models/type.rb
class Type < ActiveRecord::Base
    has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bootstrap_library_controller.rb
class BootstrapLibraryController < ApplicationController
  layout 'bolilayout'
  protect_from_forgery with: :null_session
  require 'dimensions'
  
  def index
    @types = Type.all
    @typelists = @types[1..-1] # Pick all the objects from the second to end
    @pics = Picture.all
    @clickedid = 1
    if !@pics.empty?
      @firstid = @pics.last.id
    else
      @firstid = 1
    end
    
    #Rails.logger.debug("My object: #{params[:id].inspect}")
    #Rails.logger.debug("My object: #{@pics.first.id}")
  end
  
  def show
    @types = Type.all
    @typelists = @types[1..-1] # Pick all the objects from the second to end
    
    
    if params[:id] == '1'
      @pics = Picture.all
    else
      @pics = Type.find_by_id(params[:id]).pictures
    end
    @clickedid = params[:id].to_i
    @firstid = @pics.last.id
    respond_to do |format| 
      format.js 
      format.html 
    end
    # render :layout => false
  end
  
  def create
    
    uploaded_io = params[:myform][:newimage]
    if !uploaded_io.nil? 
      File.open(Rails.root.join('app','assets','images', uploaded_io.original_filename),'wb') do |file|
        file.write(uploaded_io.read)
      end
      
      #Dimensions.dimensions(Rails.root.join('app','assets','images', uploaded_io.original_filename))  # => [300, 225]
      filewidth = Dimensions.width(Rails.root.join('app','assets','images', uploaded_io.original_filename))       # => 300
      fileheight = Dimensions.height(Rails.root.join('app','assets','images', uploaded_io.original_filename))      # => 225
      
      if params[:myform][:optionsRadios] == "optionlast"
        newtype = params[:myform][:newtype]
        checknewtype = Type.find_by_name(newtype)
        checkunknown = Type.find_by_name('Others')
        
        if newtype != ""  && checknewtype.nil? 
          Type.create(:name => newtype)
        elsif newtype == "" && checkunknown.nil?
          Type.create(:name => 'Others')
          newtype = 'Others'
        elsif newtype == "" && !checkunknown.nil?
          newtype = 'Others'
        end
        Picture.create(name: uploaded_io.original_filename, width: filewidth, height: fileheight, :type => Type.find_by_name(newtype))
        temp = Type.find_by_name(newtype)
      else
        Picture.create(name: uploaded_io.original_filename, width: filewidth, height: fileheight, :type => Type.find_by_name(params[:myform][:optionsRadios]))
        temp = Type.find_by_name(params[:myform][:optionsRadios])
      end
      
      
    end
    
    temp = temp.id
    
    @types = Type.all
    @typelists = @types[1..-1] # Pick all the objects from the second to end
    
    
    if temp == 1
      @pics = Picture.all
    else
      @pics = Type.find_by_id(temp).pictures
    end
    @clickedid = temp.to_i
    @firstid = @pics.last.id
    
    respond_to do |format| 
      format.js {render :show}
      format.html 
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_library_helper.rb
module BootstrapLibraryHelper
end

app/views/bootstrap_library/create.html.erb
<h1>BootstrapLibrary#index</h1>
<p>Find me in app/views/bootstrap_library/create.html.erb</p>

app/views/bootstrap_library/create.js.erb
$('#my-first-update').html('<%= escape_javascript render partial: 'types/type', :collection => @types, :locals => {:clickedid => @clickedid}  %>');
$('#my-second-update').html('<%= escape_javascript render partial: 'pics/pic', :collection => @pics, :locals => {:firstid => @firstid} %>');

app/views/bootstrap_library/index.html.erb
<h1>BootstrapLibrary#index</h1>
<p>Find me in app/views/bootstrap_library/index.html.erb</p>

app/views/bootstrap_library/show.html.erb
<h1>BootstrapLibrary#index</h1>
<p>Find me in app/views/bootstrap_library/index.html.erb</p>

app/views/bootstrap_library/show.js.erb
$('#my-first-update').html('<%= escape_javascript render partial: 'types/type', :collection => @types, :locals => {:clickedid => @clickedid}  %>');
$('#my-second-update').html('<%= escape_javascript render partial: 'pics/pic', :collection => @pics, :locals => {:firstid => @firstid} %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/bolilayout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  </head>
  <body>
    
    
    <div class="container-fluid">
        <div class="row justify-content-md-end align-items-center bg-success text-white" style="height: 100px;">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModalLong">
              <h1>Click me to add more photo!</h1>
            </button>
        </div>
        
        <!-- Modal -->
        <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Add new photo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form action="bootstrap_library" method="post" data-remote="true" enctype="multipart/form-data">
                  <div class="form-group">
                    <label for="exampleInputFile">Upload your photo</label>
                    <input type="file" class="form-control-file" name="myform[newimage]" id="exampleInputFile" aria-describedby="fileHelp" accept="image/*">
                    <small id="fileHelp" class="form-text text-muted">Internet is not safe! Do not upload your private photo.</small>
                  </div>
                  <fieldset class="form-group">
                    <legend>Type of the new photo</legend>
                    
                    <% if !@typelists.empty? %>
                      <%= render partial: 'typelists/typelist', :collection => @typelists %>
                    <% end %>
                   
                    <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="myform[optionsRadios]" id="optionsRadiosLast" value="optionlast"  checked>
                        New type of photo
                        <input class="form-control" type="text" name="myform[newtype]" placeholder="What is the type of it?" id="new-type-input">
                      </label>
                    </div>
                  </fieldset>
                  
                  <button type="submit" class="btn btn-primary" >Submit</button>
                </form>
              </div>
              <!--
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
              </div>
              -->
            </div>
          </div>
        </div>
        
        
        <div class="row">
            <div class="col-md-2 bg-light" style="height: 600px; overflow: scroll;">
              
              <ul class="nav flex-column">
                
                <div id="my-first-update">
                  <%= render partial: 'types/type', :collection => @types, :locals => {:clickedid => @clickedid} %>
                </div>
                    
                <!--
                <%# @types.each do |t| %>
                  <%# if params[:id] == nil %>
                    <%# if t.id == @types.first.id %>
                      <%# @keke = "active" %>
                    <%# else %>
                      <%# @keke = "disabled" %>
                    <%# end %>
                  <%# else %>
                    <%# if t.id == params[:id].to_i %>
                      <%# @keke = "active" %>
                    <%# else %>
                      <%# @keke = "disabled" %>
                    <%# end %>
                  <%# end %>
                  <li class="nav-item">
                    <%#= link_to t.name, bootstrap_library_path(t), :class => "nav-link "+ @keke, :remote => true %>
                  </li>
                <%# end %>
                -->
                
              </ul>
              
            </div>
            <div  class="col-md-10 bg-secondary justify-content-md-center align-items-center" style="height: 600px;position: relative;">
                
                
                <div id="carouselExampleIndicators" class="carousel slide bg-info " data-ride="carousel" style="position: absolute;width: 100%; height: 100%; left: 0px">
                  
                  <!--
                  <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
                  </ol>
                  -->
                  
                  
                  <div class="carousel-inner bg-info" style="position: absolute; max-width: 80%; height: 80%;left: 10%; top: 10%;"> 
                  
                    <%# @firstid = @pics.first.id %>
                    
                    <div class="text-white" id="my-second-update">
                      <%= render partial: 'pics/pic', :collection => @pics, :locals => {:firstid => @firstid} %>
                    </div>
                    
                    
                    <!--
                    <%# @pics.each do |p| %>
                      <%# if p.id == @firstid %>
                        <%# @keke = "active" %>
                      <%# else %>
                        <%# @keke = " " %>
                      <%# end %>
                      <div class="<%#= "carousel-item " + @keke %>" >
                        <img class="d-block w-100" src=<%#= "/assets/"+p.name+".jpg" %> alt="<%#= p.name+".jpg" %>" style="width: 100%; height: 500px;">
                      </div>
                    <%# end %>
                    -->
                    
                    <!--
                    <div class="carousel-item active">
                      <img class="d-block w-100" src="..." alt="First slide">
                    </div>
                    <div class="carousel-item">
                      <img class="d-block w-100" src="..." alt="Second slide">
                    </div>
                    <div class="carousel-item">
                      <img class="d-block w-100" src="..." alt="Third slide">
                    </div>
                    -->
                    
                  </div>
                  
                  
                  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
                
                
            </div>
        </div>
        <div class="row justify-content-md-end align-items-end bg-success text-white">
            <p>&copy; Copyright 2017, Luong Nguyen Corp., luong.ngtr@gmail.com </p>
        </div>
    </div>
    
    
    
    
    
  
    
    
    
    
    
    
    
    
    
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <%#= javascript_include_tag :default %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pics/_pic.html.erb
<% if pic.id == firstid %>
  <% keke = "active" %>
<% else %>
  <% keke = " " %>
<% end %>
<div class="<%= "carousel-item " + keke %>" style="position: relative;margin: 0 auto; width: <%= pic.width*500/pic.height %>px; height: 500px;">
  <img class="d-block w-100 img-fluid" src=<%= "/assets/"+ pic.name %> alt="<%= pic.name %>" style="position: relative; width: <%= pic.width*500/pic.height %>px; height: 500px;">
</div>

app/views/typelists/_typelist.html.erb
<div class="form-check">
  <label class="form-check-label">
    <input type="radio" class="form-check-input" name="myform[optionsRadios]" id="optionsRadios1" value="<%= typelist.name %>">
    <%= typelist.name %>
  </label>
</div>

app/views/types/_type.html.erb
<% if type.id == clickedid %>
  <% keke = "active" %>
<% else %>
  <% keke = "disabled" %>
<% end %>

<li class="nav-item">
    <%= link_to type.name, bootstrap_library_path(type), :class => "nav-link "+ keke, remote: true %>
</li>